- name: 1.Create a volume
  docker_volume:
    name: "data_vol_{{ etcd_name }}"
    state: present

- name: 2.start etcd-docker
  docker_container:
    name: etcd
    image: quay.io/coreos/etcd:v2.3.8
    state: started
    restart: yes
    restart_policy: always
    network_mode: host
    volumes:
     - /usr/share/ca-certificates/:/etc/ssl/certs
     - data_vol_{{ etcd_name }}:/etcd-data
    ports:
     - "4001:4001"
     - "2380:2380"
     - "2379:2379"
    env:
      ETCD_NAME: "{{ etcd_name }}"
      ETCD_ADVERTISE_CLIENT_URLS: "http://{{ ansible_eth0.ipv4.address }}:2379,http://{{ ansible_eth0.ipv4.address }}:4001"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379,http://0.0.0.0:4001"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://{{ ansible_eth0.ipv4.address }}:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_INITIAL_CLUSTER_TOKEN: "{{initial_cluster_token}}"
      ETCD_INITIAL_CLUSTER: "{{ hostvars['m0']['etcd_name'] }}=http://{{ hostvars['m0']['ansible_host'] }}:2380,{{ hostvars['m1']['etcd_name'] }}=http://{{ hostvars['m1']['ansible_host'] }}:2380,{{ hostvars['m2']['etcd_name'] }}=http://{{ hostvars['m2']['ansible_host'] }}:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
      ETCD_DATA_DIR: /etcd-data
