- name: start etcd-docker
  docker_container:
    name: etcd
    image: quay.io/coreos/etcd:v2.3.8
    state: absent
    restart: yes
    network_mode: host
    volumes:
     - /usr/share/ca-certificates/:/etc/ssl/certs
    exposed_ports:
      - 4001
      - 2380
      - 2379
    published_ports:
     - "4001:4001"
     - "2380:2380"
     - "2379:2379"
    command: >
      -name {{ etcd_name }}
      -advertise-client-urls http://{{ ansible_eth0.ipv4.address }}:2379,http://{{ ansible_eth0.ipv4.address }}:4001
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      -initial-advertise-peer-urls http://{{ ansible_eth0.ipv4.address }}:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token etcd-cluster-1
      -initial-cluster {{ etcd_name }}=http://{{ ansible_eth0.ipv4.address }}:2380,{{ etcd_name }}=http://{{ ansible_eth0.ipv4.address }}:2380,{{ etcd_name }}=http://{{ ansible_eth0.ipv4.address }}:2380
      -initial-cluster-state new
  become: true


# - name: install etcd-docker
#   shell: 'docker run -d -v /usr/share/ca-certificates/:/etc/ssl/certs -p 4001:4001 -p 2380:2380 -p 2379:2379 --name etcd quay.io/coreos/etcd:v2.3.8 -name {{ etcd_name }} -advertise-client-urls http://{{ ansible_eth0.ipv4.address }}:2379,http://{{ ansible_eth0.ipv4.address }}:4001 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls http://{{ ansible_eth0.ipv4.address }}:2380 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster-1 -initial-cluster etcd0=http://{{ ansible_eth0.ipv4.address }}:2380,etcd1=http://{{ ansible_eth0.ipv4.address }}:2380,etcd2=http://{{ ansible_eth0.ipv4.address }}:2380 -initial-cluster-state new'
#   become: true
